#!/bin/bash

echo "🎯 ALL AVAILABLE TESTS FOR YOUR TECHCARE BACKEND"
echo "================================================="
echo ""

echo "📋 CUSTOMER AUTHENTICATION TESTS:"
echo "=================================="
echo "1. ✅ Customer signup, login, logout, profile"
echo "2. ✅ Customer image upload"
echo "3. ✅ Customer profile update"
echo "4. ✅ Customer password reset (NEW!)"
echo ""

echo "🧪 AVAILABLE TEST SCRIPTS:"
echo "=========================="
echo ""

echo "Customer Profile & Image Tests:"
echo "-------------------------------"
echo "• ./test_update_profile.sh - Test profile updates"
echo "• ./test_image_upload.sh - Test image upload"
echo "• ./test_profile_update.sh - Test profile update with image"
echo "• ./test_complete_customer_service.sh - Complete customer service test"
echo ""

echo "Password Reset Tests (NEW!):"
echo "----------------------------"
echo "• ./quick_test_password_reset.sh - Quick 1-command test"
echo "• ./test_password_reset.sh - Basic password reset test"
echo "• ./test_complete_password_reset.sh - Complete flow test"
echo ""

echo "Documentation & Guides:"
echo "------------------------"
echo "• ./HOW_TO_TEST_PASSWORD_RESET.sh - Complete testing guide"
echo "• ./password_reset_summary.sh - Feature implementation summary"
echo "• PASSWORD_RESET_API.md - API documentation"
echo "• CUSTOMER_IMAGE_UPLOAD_API.md - Image upload documentation"
echo ""

echo "🚀 RECOMMENDED TESTING ORDER:"
echo "============================="
echo ""
echo "Step 1: Start Backend Application"
echo "----------------------------------"
echo "cd /home/prince/tech-care/backend"
echo "mvn spring-boot:run"
echo ""
echo "Wait for: 'Started TechCareRwandaApplication in X seconds'"
echo ""

echo "Step 2: Test Customer Authentication"
echo "-----------------------------------"
echo "./test_complete_customer_service.sh"
echo ""

echo "Step 3: Test Password Reset Feature"
echo "----------------------------------"
echo "./quick_test_password_reset.sh"
echo ""

echo "Step 4: Test Profile & Image Updates"
echo "-----------------------------------"
echo "./test_update_profile.sh"
echo ""

echo "🔧 QUICK COMMANDS FOR IMMEDIATE TESTING:"
echo "========================================"
echo ""

echo "# Test password reset right now:"
echo "./quick_test_password_reset.sh"
echo ""

echo "# Test profile updates:"
echo "./test_update_profile.sh"
echo ""

echo "# Test image upload:"
echo "./test_image_upload.sh"
echo ""

echo "# See all customer endpoints:"
echo "./test_complete_customer_service.sh"
echo ""

echo "📱 POSTMAN COLLECTION ENDPOINTS:"
echo "================================"
echo ""
echo "Customer Authentication:"
echo "• POST /api/v1/customer/signup"
echo "• POST /api/v1/customer/login"
echo "• GET /api/v1/customer/profile"
echo "• POST /api/v1/customer/logout"
echo "• GET /api/v1/customer/check-auth"
echo ""
echo "Customer Profile Management:"
echo "• POST /api/v1/customer/upload-image"
echo "• PUT /api/v1/customer/update-profile"
echo ""
echo "Password Reset (NEW!):"
echo "• POST /api/v1/customer/forgot-password"
echo "• POST /api/v1/customer/reset-password"
echo ""

echo "🎉 WHAT'S WORKING:"
echo "=================="
echo "✅ Customer signup with email confirmation"
echo "✅ Customer login with JWT tokens"
echo "✅ Customer profile management"
echo "✅ Customer image upload and serving"
echo "✅ Customer profile updates"
echo "✅ Customer password reset (NEW!)"
echo "✅ Secure authentication and authorization"
echo "✅ CORS configuration for frontend"
echo "✅ Error handling and validation"
echo "✅ Email notifications"
echo ""

echo "🔥 READY TO TEST!"
echo "=================="
echo "Your TechCare backend is fully equipped with:"
echo "• Complete customer authentication system"
echo "• Image upload and profile management"
echo "• Secure password reset functionality"
echo "• Comprehensive test suite"
echo "• Professional email templates"
echo "• API documentation"
echo ""
echo "Pick any test script above and start testing! 🚀"
echo ""
