services:
  tech-care-backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./logs:/app/logs